// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Core.Entities;
using System;
using System.Collections.Generic;

namespace Entities.Models
{
    public partial class InvoiceDetails : IEntity
    {
        public int Id { get; set; }
        public int? ProductId { get; set; }
        public int? InvoiceId { get; set; }

        public virtual Invoices Invoice { get; set; }
        public virtual Products Product { get; set; }
    }
}