// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Core.Entities;
using System;
using System.Collections.Generic;

namespace Entities.Models
{
    public partial class Invoices : IEntity
    {
        public int Id { get; set; }
        public int? CustomerId { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? ExpiredOn { get; set; }
        public decimal? Total { get; set; }
        public int? Discount { get; set; }
    }
}